dist: xenial
sudo: false

language: node_js
node_js:
  - '14.15'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
    chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install
  - npm install -g codecov

before_script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  
script:
  - ng build
  - npm run build
  
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
  - codecov --disable=gcov 