dist: xenial
sudo: false

language: node_js
node_js:
  - '14.15'

addons:
  apt:
    chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install -g @angular/cli
  - npm install -g @angular-devkit/build-angular
  - npm install -g firebase-tools
  - pip install --user codecov

script:
  - npm run test --watch=false --browsers=ChromeHeadless
  - npm run build
  
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
  - codecov --disable=gcov