language: python
python:
  - "3.7"
env:
  - CODECOV_TOKEN='75200cc1-b931-4cbf-9cc8-beeec1751772'
  
install:
  - pip install codecov
  
script:
  - coverage run test.py

after_success:
  - codecov

cache: pip
install:
  - pip install -r package.json
script:
  - python test.py